export const COPY = {
  headerBadge: '🇮🇳 Gratuity Act, 1972',
  pageTitle: 'Gratuity Calculator',
  pageSubtitle: "Find out how much gratuity you're owed.",
  resultLabel: 'Your Gratuity',
  amountNotEligible: '—',
  eligiblePillPrefix: 'Eligible',
  notEligiblePillPrefix: 'Not eligible',
  yearsCountedSuffix: 'yrs counted',
  nudgeYearsTemplate: 'Need {N} more year(s) to be close.',
  nudgeMonthsTemplate: "Add {N} more month(s) and you'll qualify.",
  monthlySalaryLabel: 'Monthly Salary (Basic + DA)',
  currencyPrefix: '₹',
  monthlySuffix: '/ month',
  yearsOfServiceLabel: 'Years of Service',
  yearsSliderLabel: 'Years',
  extraMonthsLabel: 'Extra Months',
  roundsUpBadge: 'rounds up ↑',
  monthsFooterLeft: '0 mo',
  monthsFooterCenter: '6+ rounds up',
  monthsFooterRight: '11 mo',
  footerLineOne: 'Based on the Payment of Gratuity Act, 1972.',
  footerLineTwo: 'Payout capped at ₹20L. This is an estimate.',
} as const
