export const COPY = {
  headerBadge: '🇮🇳 Gratuity Act, 1972',
  pageTitle: 'Gratuity Calculator',
  pageSubtitle: 'તમને કેટલી Gratuity મળશે તે જાણો.',
  resultLabel: 'તમારી Gratuity',
  amountNotEligible: '—',
  eligiblePillPrefix: 'પાત્ર',
  notEligiblePillPrefix: 'અપાત્ર',
  yearsCountedSuffix: 'વર્ષ ગણાયા',
  nudgeYearsTemplate: 'Need {N} more year(s) to be close.',
  nudgeMonthsTemplate: "Add {N} more month(s) and you'll qualify.",
  monthlySalaryLabel: 'માસિક પગાર (Basic + DA)',
  currencyPrefix: '₹',
  monthlySuffix: '/ મહિનો',
  yearsOfServiceLabel: 'નોકરીનાં વર્ષો',
  yearsSliderLabel: 'વર્ષ',
  extraMonthsLabel: 'વધારાના મહિના',
  roundsUpBadge: 'ઉપર ગણાય ↑',
  monthsFooterLeft: '0 મહિનો',
  monthsFooterCenter: '6+ ઉપર ગણાય',
  monthsFooterRight: '11 મહિના',
  footerLineOne: 'Payment of Gratuity Act, 1972 પર આધારિત.',
  footerLineTwo: 'મહત્તમ ચુકવણી ₹20 લાખ. આ એક અંદાજ છે.',
} as const
